### PR TITLE
Add markdown capitalization linting, fix errors

### PR DESCRIPTION
**Pull request by dfarrell07**
For a more consistent and easier review process, and for higher quality
docs results.

Copies markdownlint configuration from the website.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
These failures seem to be on usages that are in `code blocks`. The config should ignore anything in code blocks. I think this works, using the same config, in the website CI.

```
Error: submariner-operator/diagnose-refactor-ocm.md:22:20 MD044/proper-names Proper names should have the correct capitalization [Expected: Submariner; Actual: submariner]
Error: submariner-operator/diagnose-refactor-ocm.md:24:9 MD044/proper-names Proper names should have the correct capitalization [Expected: Submariner; Actual: submariner]
Error: submariner-operator/diagnose-refactor-ocm.md:2[8](https://github.com/submariner-io/enhancements/runs/6099105497?check_suite_focus=true#step:4:8):38 MD044/proper-names Proper names should have the correct capitalization [Expected: Submariner; Actual: submariner]
Error: submariner-operator/diagnose-refactor-ocm.md:43:[9](https://github.com/submariner-io/enhancements/runs/6099105497?check_suite_focus=true#step:4:9) MD044/proper-names Proper names should have the correct capitalization [Expected: Submariner; Actual: submariner]
```

I don't see these failures locally.

```
[~/go/src/submariner-io/enhancements]$ markdownlint markdownlint -c .markdownlint.yml .
[~/go/src/submariner-io/enhancements]$ echo $?
0
[~/go/src/submariner-io/enhancements]$ markdownlint --version
0.28.1
```

Need to dig into the versions more. The GHA version in the website is different than the one here. Need to get all of them auto-updating to latest with the new Dependabot support for SHAs for GHA.

**Comment by nyechiel** [comment]
@dfarrell07 are you working on this for 0.13?

**Comment by dfarrell07** [comment]
I think this should work now that the GHAs are auto-updated. Need to manual rebase.

**Comment by dfarrell07** [comment]
This seems to be correctly failing now.

**Review by mkolesnik — COMMENTED** [review]
I wonder if it would be a better idea to enhance the `markdownlint` target in Shipyard to consume a shared `.markdownlint.yml` config file (that we can ship in the image) and merge it with any local `.markdownlint.yml` file.

It seems the `markdownlint` command itself doent support multiple config files, but we can overcome it by merging them to a temp file.
Merging can be done with https://mikefarah.gitbook.io/yq/commands/evaluate-all (though the example Isn't very good, as outlined here - https://stackoverflow.com/a/68760391

**Pull request closed without merging**
